"""Document automation endpoints — auto-generate UK energy application forms."""

from __future__ import annotations

import logging

from fastapi import APIRouter, HTTPException, Query
from pydantic import BaseModel

from utils.document_automation import generate_document, get_document_checklist

log = logging.getLogger("princeps.documents")
router = APIRouter(tags=["documents"])


# ---------------------------------------------------------------------------
# Request models
# ---------------------------------------------------------------------------

class DocumentGenerateRequest(BaseModel):
    """Payload for POST /api/documents/generate."""
    document_type: str
    site: dict = {}
    capacity: dict = {}
    grid: dict = {}
    technology: dict = {}
    assessment: dict = {}
    constraints: dict = {}
    timeline: dict = {}
    geeflow_data: dict = {}
    capacity_mw: float | None = None
    capacity_kw: float | None = None


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@router.post("/api/documents/generate")
async def api_generate_document(req: DocumentGenerateRequest):
    """Generate a pre-filled UK energy development application document.

    Supported document_type values:
    - g99_application: G99 Grid Connection Application (Parts 1-4b)
    - planning_summary: Planning Application Summary (1APP key sections)
    - eia_screening: EIA Screening Request (Schedule 2 criteria)
    - cdm_f10: CDM F10 Notification (HSE pre-fill)
    - bng_baseline: BNG Baseline Assessment (simplified biodiversity metric)
    - licence_memo: Generation Licence Exemption Memo

    Returns form_data (structured dict), html (PDF-ready), document_type, and
    auto_fill_pct indicating how much was auto-populated from assessment data.
    """
    try:
        result = generate_document(
            document_type=req.document_type,
            data=req.model_dump(),
        )
    except ValueError as e:
        raise HTTPException(status_code=422, detail=str(e))
    except Exception as e:
        log.exception("Document generation failed: %s", req.document_type)
        raise HTTPException(
            status_code=500,
            detail=f"Document generation failed: {e}",
        )
    return result


@router.get("/api/documents/checklist")
async def api_document_checklist(
    capacity_kw: float = Query(..., description="Proposed capacity in kW"),
    technology: str = Query("solar", description="Technology: solar, wind, bess"),
    flood_zone: int = Query(1, description="EA flood zone: 1, 2, or 3"),
    agricultural_grade: int = Query(4, description="ALC grade: 1-5"),
    aonb: bool = Query(False, description="Site in AONB / National Landscape"),
    sssi: bool = Query(False, description="Site near SSSI"),
    green_belt: bool = Query(False, description="Site in Green Belt"),
    conservation_area: bool = Query(False, description="Site in conservation area"),
    listed_buildings: bool = Query(False, description="Listed buildings nearby"),
    includes_bess: bool = Query(False, description="Project includes battery storage"),
    area_ha: float = Query(0, description="Site area in hectares"),
):
    """Return a checklist of all required documents for a given project.

    Based on capacity, technology, and site constraints, identifies which
    UK regulatory documents are required, their typical lead times, and
    which can be auto-generated by Princeps.
    """
    constraints = {
        "flood_zone": flood_zone,
        "agricultural_grade": agricultural_grade,
        "aonb": aonb,
        "sssi": sssi,
        "green_belt": green_belt,
        "conservation_area": conservation_area,
        "listed_buildings": listed_buildings,
        "includes_bess": includes_bess,
        "area_ha": area_ha,
    }
    try:
        result = get_document_checklist(
            capacity_kw=capacity_kw,
            technology=technology,
            constraints=constraints,
        )
    except Exception as e:
        log.exception("Document checklist generation failed")
        raise HTTPException(
            status_code=500,
            detail=f"Checklist generation failed: {e}",
        )
    return result


@router.get("/api/documents/types")
async def api_document_types():
    """List all supported document types with descriptions."""
    return {
        "document_types": [
            {
                "id": "g99_application",
                "name": "G99 Grid Connection Application",
                "description": "ENA EREC G99 Issue 2 — Parts 1-4b pre-filled from assessment data",
                "required_fields": ["site", "capacity", "grid", "technology"],
            },
            {
                "id": "planning_summary",
                "name": "Planning Application Summary (1APP)",
                "description": "Key sections of 1APP form pre-filled from GeeFlow and assessment data",
                "required_fields": ["site", "assessment", "constraints"],
            },
            {
                "id": "eia_screening",
                "name": "EIA Screening Request",
                "description": "Schedule 2 criteria assessment with sensitivity analysis and effects checklist",
                "required_fields": ["site", "capacity_mw", "constraints"],
            },
            {
                "id": "cdm_f10",
                "name": "CDM F10 Notification",
                "description": "HSE F10 form pre-filled with project details, workforce, and key risks",
                "required_fields": ["site", "capacity_mw", "timeline"],
            },
            {
                "id": "bng_baseline",
                "name": "BNG Baseline Assessment",
                "description": "Simplified Statutory Biodiversity Metric (v1.0) using DynamicWorld satellite classification",
                "required_fields": ["site", "geeflow_data"],
            },
            {
                "id": "licence_memo",
                "name": "Generation Licence Exemption Memo",
                "description": "Confirms exemption status under Electricity (Class Exemptions) Order 2001",
                "required_fields": ["capacity_kw"],
            },
        ],
    }
