"""PVsyst .PRJ exporter.

PVsyst projects (.PRJ / .VP{M,D,N}) are Windows-INI-style text files. The full
schema is proprietary and versioned, but the high-level block structure is
stable enough for round-tripping a basic site+system definition into PVsyst
Professional, where the user can then tune module/inverter selection and
rerun simulation.

Scope of this exporter
----------------------
- Emit a readable `.PRJ` text file covering [Project], [Site], [Meteo],
  [System], [Shading] and [Simulation] blocks.
- Use data from ``site_layouts`` (PostGIS) if available, else fall back to
  placeholders commented with the field name so the human can fill them in.
- Not a substitute for running PVsyst — it produces a STARTING point.

Public API
----------
    export_pvsyst_project(site_id, layout_id, out_path, *, pool=None) -> Path
"""

from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
from uuid import UUID

log = logging.getLogger("princeps.export.pvsyst")

# PVsyst expects CRLF + ANSI (we write UTF-8; modern PVsyst handles it).
_NL = "\r\n"


def _ini_block(name: str, fields: dict[str, Any]) -> str:
    """Emit an INI-style block. None values become 'TBC' with a comment."""
    lines = [f"[{name}]"]
    for k, v in fields.items():
        if v is None:
            lines.append(f";   {k} not available from Princeps site data — FILL IN PVsyst")
            lines.append(f"{k}=TBC")
        elif isinstance(v, float):
            lines.append(f"{k}={v:.6g}")
        elif isinstance(v, bool):
            lines.append(f"{k}={'True' if v else 'False'}")
        else:
            lines.append(f"{k}={v}")
    return _NL.join(lines) + _NL


def _safe_float(v: Any) -> float | None:
    try:
        return float(v) if v is not None else None
    except (TypeError, ValueError):
        return None


async def _load_layout(pool, site_id: UUID | str, layout_id: UUID | str | None) -> dict:
    """Pull what we can from the DB. Missing tables / rows → empty dict."""
    data: dict[str, Any] = {}
    if pool is None:
        return data
    try:
        async with pool.acquire() as conn:
            layout = None
            if layout_id:
                layout = await conn.fetchrow(
                    """SELECT parcel_id, layout_data, updated_at
                       FROM site_layouts WHERE parcel_id = $1""",
                    layout_id,
                )
            if layout:
                raw = layout["layout_data"]
                if isinstance(raw, str):
                    raw = json.loads(raw)
                data["layout"] = raw or {}
                data["layout_updated_at"] = layout["updated_at"]
            # Best-effort site lookup (parcel centroid, area, land use).
            parcel = await conn.fetchrow(
                """SELECT parcel_id,
                          ST_Y(ST_Transform(centroid, 4326)) AS lat,
                          ST_X(ST_Transform(centroid, 4326)) AS lon,
                          area_m2
                   FROM parcels WHERE parcel_id = $1""",
                layout_id or site_id,
            )
            if parcel:
                data["lat"] = _safe_float(parcel["lat"])
                data["lon"] = _safe_float(parcel["lon"])
                data["area_m2"] = _safe_float(parcel["area_m2"])
    except Exception as e:  # noqa: BLE001
        log.info("pvsyst export: db lookup failed (%s) — falling back to placeholders", e)
    return data


def _build_content(
    *,
    project_name: str,
    lat: float | None,
    lon: float | None,
    elevation_m: float | None,
    capacity_mw_dc: float | None,
    tilt_deg: float | None,
    azimuth_deg: float | None,
    dc_ac_ratio: float | None,
    layout_json: dict | None,
    now_iso: str,
) -> str:
    modules_count = None
    if layout_json:
        for key in ("modules_count", "panel_count", "n_modules"):
            if layout_json.get(key) is not None:
                modules_count = int(layout_json[key])
                break

    module_wp = None
    if layout_json and layout_json.get("module_wp"):
        module_wp = int(layout_json["module_wp"])
    elif capacity_mw_dc and modules_count:
        module_wp = int(round((capacity_mw_dc * 1e6) / modules_count))

    inverter_kw = None
    if capacity_mw_dc and dc_ac_ratio:
        inverter_kw = round(capacity_mw_dc * 1000.0 / dc_ac_ratio, 1)

    header = [
        f"PVsyst={_SUPPORTED_VERSION}",
        f";  Generated by Princeps AI Platform on {now_iso}",
        f";  Principle: starting point only. Review all fields in PVsyst Pro.",
        f";  Any line starting ';' is a comment.",
        "",
    ]

    blocks = [
        _ini_block("Project", {
            "Name": project_name,
            "Version": "1",
            "Author": "Princeps AI Platform",
            "Created": now_iso,
            "Simulation": "Grid-connected",
            "FileVersion": _SUPPORTED_VERSION,
        }),
        _ini_block("Site", {
            "Name": project_name,
            "Latitude_deg": lat,
            "Longitude_deg": lon,
            "Altitude_m": elevation_m,
            "TimeZone": _tz_from_lon(lon),
            "Albedo": 0.20,
        }),
        _ini_block("Meteo", {
            # Reference a generic TMY — user imports the real one in PVsyst.
            "Source": "TMY (user to attach via PVsyst Meteo DB)",
            "SiteFile": f"{project_name}.MET",
            "Model": "Hourly",
        }),
        _ini_block("Orientation", {
            "Type": "Fixed plane",
            "Tilt_deg": tilt_deg if tilt_deg is not None else 30.0,
            "Azimuth_deg": azimuth_deg if azimuth_deg is not None else 180.0,
        }),
        _ini_block("System", {
            "NominalPowerDC_kWp": (capacity_mw_dc * 1000.0) if capacity_mw_dc else None,
            "ModulesInSeries": (layout_json or {}).get("modules_in_series"),
            "Strings": (layout_json or {}).get("string_count"),
            "Module_Wp": module_wp,
            "Module_DB_ref": "Generic_400W_Mono_PERC",
            "Inverter_kW": inverter_kw,
            "Inverter_DB_ref": "Generic_1500V_Central",
            "DC_AC_ratio": dc_ac_ratio,
        }),
        _ini_block("Losses", {
            "ThermalLoss_UcW_m2K": 29.0,
            "OhmicWiring_pct": 1.5,
            "ModuleMismatch_pct": 1.0,
            "Soiling_pct": 2.0,
            "SpectralCorrection_pct": 0.0,
            "LID_pct": 1.5,
            "Availability_pct": 1.0,
        }),
        _ini_block("Shading", {
            "Scene3D": "linked .SHD file — add in PVsyst",
            "NearShading": (layout_json or {}).get("near_shading") or False,
            "SelfShading": (layout_json or {}).get("self_shading") or True,
        }),
        _ini_block("Simulation", {
            "Type": "Hourly",
            "UseMetricTMY": True,
            "Verbose": True,
        }),
        _ini_block("PrincepsProvenance", {
            "GeneratedAt": now_iso,
            "LayoutCount": int(bool(layout_json)),
            "Capacity_MWdc": capacity_mw_dc,
            "Note": "See Princeps site for live grid + planning context.",
        }),
    ]
    return _NL.join(header) + _NL.join(blocks)


def _tz_from_lon(lon: float | None) -> int:
    """Crude time-zone from longitude. UK ~= 0."""
    if lon is None:
        return 0
    return int(round(lon / 15.0))


_SUPPORTED_VERSION = "7.4"


async def export_pvsyst_project(
    site_id: str | UUID,
    layout_id: str | UUID | None,
    out_path: str | Path,
    *,
    pool=None,
    project_name: str | None = None,
    capacity_mw_dc: float | None = None,
    tilt_deg: float | None = None,
    azimuth_deg: float | None = None,
    dc_ac_ratio: float | None = 1.3,
    elevation_m: float | None = None,
) -> Path:
    """Write a PVsyst-compatible project file. Returns the path written.

    Missing DB data is replaced with placeholders — PVsyst will still open the
    file and flag TBC fields.
    """
    out = Path(out_path)
    out.parent.mkdir(parents=True, exist_ok=True)

    ctx = await _load_layout(pool, site_id=site_id, layout_id=layout_id)
    layout = ctx.get("layout") or {}
    lat = ctx.get("lat")
    lon = ctx.get("lon")
    area_m2 = ctx.get("area_m2")

    if capacity_mw_dc is None:
        capacity_mw_dc = _safe_float(layout.get("capacity_mw_dc")) \
            or (_safe_float(layout.get("installed_capacity_mw")))
        if capacity_mw_dc is None and area_m2:
            # Rough default: 0.6 MW per ha for ground-mounted PV.
            capacity_mw_dc = round((area_m2 / 10000.0) * 0.6, 2)

    content = _build_content(
        project_name=project_name or str(layout.get("name") or site_id),
        lat=lat, lon=lon, elevation_m=elevation_m,
        capacity_mw_dc=capacity_mw_dc,
        tilt_deg=tilt_deg or _safe_float(layout.get("tilt_deg")),
        azimuth_deg=azimuth_deg or _safe_float(layout.get("azimuth_deg")),
        dc_ac_ratio=dc_ac_ratio,
        layout_json=layout,
        now_iso=datetime.now(timezone.utc).isoformat(),
    )
    out.write_text(content, encoding="utf-8", newline="")
    log.info("pvsyst export: %d bytes -> %s", len(content), out)
    return out


# Synchronous convenience wrapper for callers without an event loop handy.

def export_pvsyst_project_sync(*args, **kwargs) -> Path:
    import asyncio
    return asyncio.run(export_pvsyst_project(*args, **kwargs))
